spring:
  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
    driverClassName: ${driverClassName}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true